engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpmd:
    enabled: true
ratings:
  paths:
  - src/**
  - "*.php"
exclude_paths:
  - tests/**/*
  - vendor/**/*