language: php
php:
  - '5.6'
  - '7.0'

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search

composer install

script: phpunit --coverage-text
