language: php
php:
  - '5.6'
  - '7.0'
addons:
    code_climate:
        repo_token: ce6fe1b4b137a9b37dcae62ee6eee5585b621e286fdd4ae576974b800a6bcdd2
script:
  - composer install
  - phpunit --configuration phpunit.xml ./tests --coverage-text --coverage-clover build/logs/clover.xml
